[package]
name = "bitcoin-peer"
version = "0.1.0"
authors = ["Dr. Maxim Orlovsky <dr.orlovsky@gmail.com>"]

[dependencies]
bitcoin = { git = "https://github.com/dr-orlovsky/rust-bitcoin.git" }
aerospike = "0.3.0"